# Generated by Django 4.2.16 on 2024-09-10 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("price", models.IntegerField()),
                ("description", models.TextField()),
                ("category", models.CharField(blank=True, max_length=50, null=True)),
                ("stock", models.PositiveBigIntegerField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="product_images/"
                    ),
                ),
                ("brand", models.CharField(blank=True, max_length=50, null=True)),
                ("sold", models.BooleanField(default=False)),
            ],
        ),
    ]
