# Generated by Django 4.2.16 on 2024-09-10 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_product_condition"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="sold",),
    ]
