# Generated by Django 4.2.16 on 2024-09-10 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_remove_product_sold"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="product",
            name="condition",
            field=models.CharField(max_length=50),
        ),
    ]
