# Generated by Django 4.2.16 on 2024-09-17 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_product_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("clothes", "Clothes"),
                    ("bag", "Bag"),
                    ("shoes", "Shoes"),
                    ("accessories", "Accessories"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="condition",
            field=models.CharField(
                choices=[("fair", "Fair"), ("good", "Good"), ("like new", "Like New")],
                max_length=50,
            ),
        ),
    ]
