# Generated by Django 4.2.16 on 2024-09-17 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_alter_product_category_alter_product_condition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("Clothes", "Clothes"),
                    ("Bag", "Bag"),
                    ("Shoes", "Shoes"),
                    ("Accessories", "Accessories"),
                    ("Other", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="condition",
            field=models.CharField(
                choices=[("Fair", "Fair"), ("Good", "Good"), ("Like New", "Like New")],
                max_length=50,
            ),
        ),
    ]
