# Generated by Django 4.2.16 on 2024-11-14 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_product_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
